services:
  - type: web
    name: sensei-fastapi
    env: python
    plan: free
    buildCommand: |
      pip install pipenv
      pipenv install --deploy --ignore-pipfile
    startCommand: pipenv run uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FIREBASE_KEY_PATH
        value: /etc/secrets/firebasekey.json
      - key: JWT_SECRET_KEY
    autoDeploy: true
    env: 
      - key: PYTHON_VERSION
        value: 3.12
    disk:
      name: firebase-key
      mountPath: /etc/secrets
      sizeGB: 1